In [1]:
# Import necessary libraries for data analysis and cleaning
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# Clean Drug

In [2]:
# Load the drug dataset
df_drug = pd.read_csv('stratified_drug_200_withText_first.csv')

# Display basic information about the dataset
print("Dataset Shape:", df_drug.shape)
print("\nFirst few rows:")
df_drug.head()

Dataset Shape: (200, 37)

First few rows:

,Respondent_ID,Q1_Age,Q2_Gender,Q3_Education,Q4_Employment,Q5_FamilyFinance,Q6_HomeLocation,Q7_FamilyHistory,Q8.1_Stress,Q8.2_PeerPressure,Q8.3_Normality,Q8.4_ExploreIdentity,Q8.5_HomeProblem,Q8.6_ConfidentToSayNo,Q9_Beliefs,Q10_MoralFailing,Q11_Penalties,Q12_FirstTimeMotivation,Q13_SocialAttitude,Q14_EverUsed,Q15_FirstUseAge,Q16_WeeklySpend,Q17_Cannabis,Q17_Cocaine,Q17_Ecstasy,Q17_Heroin,Q17_Meth,Q17_Prescription,Q17_Psychedelics,Q18_Frequency,Q19_Setting,Q20_InterestInHelp,Q21.1_SchoolEd,Q21.2_ParentalGuide,Q21.3_Commu,Q21.4_PublicCamp,Q21.5_MentalHealth
0,1420.738068,16.375643,Male,1,Self-employed,Struggled to meet basic needs,A large city,Yes,2.829408,4.652830,3.741620,3.961340,3.289067,1.829930,1.720772,1.507691,1.627269,To seek a 'high' or plessure,"Mixed or polarized (e.g., some are for it, others are strongly against it)",Yes,15.414717,46.412030,No,No,Yes,No,No,No,No,Once a week,At home alone,"Yes, considering",3.103695,4.665427,1.351523,4.120069,3.960874
1,1776.940502,16.512084,Female,2,Self-employed,"Comfortable, able to meet most needs",A town,No,2.210867,4.288344,3.390074,2.671188,2.206759,3.032348,2.305348,1.985666,2.948480,To relieve stress or anxiety,"Negative and stigmatized (e.g., seen as dangerous or a moral failing)",Yes,15.685731,13.628316,Yes,No,Yes,No,No,No,No,1-3 times a month,At a party or social gathering,"Yes, considering",1.916425,1.607843,3.247999,2.462481,3.678290
2,978.278278,16.678701,Male,2,Student,Struggled to meet basic needs,A large city,Yes,3.515320,4.583834,3.051474,3.229196,4.108366,1.650940,2.338922,1.829399,1.424426,Curiosity,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,15.741856,17.294067,Yes,No,Yes,No,No,No,Yes,Once a week,At a party or social gathering,"Yes, actively",3.900180,3.442723,2.439595,4.506142,4.390143
3,1999.648147,16.830390,Male,1,Unemployed,Struggled to meet basic needs,A town,Yes,2.709628,4.350584,4.261498,2.794694,2.744706,1.532134,2.464115,1.792312,2.415800,To cope with boredom,"Mixed or polarized (e.g., some are for it, others are strongly against it)",Yes,15.837079,16.553909,Yes,No,No,No,No,No,Yes,Once a week,At a friend's house,"Yes, considering",1.081258,1.004996,2.060437,3.002572,2.443862
4,1712.207719,16.972754,Female,1,Employed full-time,"Met basic needs, but with some difficulty",A large city,Yes,3.298162,4.405629,3.749170,3.532261,2.798519,1.801919,2.105547,1.894520,2.773848,To escape problems,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,16.666253,40.511459,Yes,No,No,No,No,No,No,Once a week,"Outdoors (e.g., park, street)","Yes, considering",2.062181,3.078571,1.709446,2.110821,2.875520

In [3]:
# Sort the DataFrame by 'respondent_ID'
df_drug.sort_values(by='Respondent_ID', inplace=True)

# Reset the 'Respondent_ID' column to be a sequence from 1 to 200
df_drug['Respondent_ID'] = np.arange(1, len(df_drug) + 1)

# Display the first few rows to verify the changes
df_drug.head()

,Respondent_ID,Q1_Age,Q2_Gender,Q3_Education,Q4_Employment,Q5_FamilyFinance,Q6_HomeLocation,Q7_FamilyHistory,Q8.1_Stress,Q8.2_PeerPressure,Q8.3_Normality,Q8.4_ExploreIdentity,Q8.5_HomeProblem,Q8.6_ConfidentToSayNo,Q9_Beliefs,Q10_MoralFailing,Q11_Penalties,Q12_FirstTimeMotivation,Q13_SocialAttitude,Q14_EverUsed,Q15_FirstUseAge,Q16_WeeklySpend,Q17_Cannabis,Q17_Cocaine,Q17_Ecstasy,Q17_Heroin,Q17_Meth,Q17_Prescription,Q17_Psychedelics,Q18_Frequency,Q19_Setting,Q20_InterestInHelp,Q21.1_SchoolEd,Q21.2_ParentalGuide,Q21.3_Commu,Q21.4_PublicCamp,Q21.5_MentalHealth
156,1,22.127394,Female,2,Unemployed,Struggled to meet basic needs,A town,No,3.547701,3.088500,3.029201,3.309207,3.783110,3.559964,1.714293,2.421095,1.206965,To relieve stress or anxiety,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,16.521356,66.305076,Yes,Yes,No,No,No,No,No,Once a week,At a friend's house,"Yes, considering",4.843801,4.890829,2.455424,3.979657,3.942842
10,2,17.758969,Male,2,Unemployed,"Met basic needs, but with some difficulty",A rural area,Yes,2.054012,4.198952,2.209783,3.523866,2.445294,3.697164,2.077526,2.294953,2.120109,To relieve stress or anxiety,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,16.037890,34.316943,Yes,No,No,No,Yes,No,Yes,1-3 times a month,At a friend's house,"Yes, considering",4.666446,4.936028,4.572778,4.850803,4.881922
82,3,20.448496,Female,2,Student,"Comfortable, able to meet most needs",A town,Yes,1.856025,2.221508,1.203511,3.485828,2.034008,4.299885,2.841853,2.973249,3.605458,To relieve stress or anxiety,"Negative and stigmatized (e.g., seen as dangerous or a moral failing)",Yes,17.750215,60.949473,Yes,No,No,No,No,No,No,1-3 times a month,At a friend's house,Not sure,3.291726,4.741208,2.045189,2.730219,3.795337
183,4,23.281481,Female,3,Unemployed,"Met basic needs, but with some difficulty",A large city,No,2.652465,1.345772,1.482590,1.612894,2.593072,4.353729,2.661659,2.887705,1.902963,Curiosity,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,17.846764,29.391190,Yes,No,No,No,No,No,No,Once a week,At a friend's house,Not sure,2.374819,2.566840,1.655841,1.889158,2.340117
107,5,20.910383,Female,4,Self-employed,"Met basic needs, but with some difficulty",A large city,No,1.484414,2.710875,1.582764,1.739131,1.796326,3.645108,2.773359,4.208610,2.664736,To cope with boredom,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,18.827544,26.006703,Yes,No,No,No,No,No,No,Less than once a month,"Outdoors (e.g., park, street)",No,3.924744,3.428508,2.124466,3.670147,4.086584

In [4]:
# Identify columns that contain 'Age' in their name
age_columns = [col for col in df_drug.columns if 'Age' in col]

# Round the values in these columns to 0 decimal places
for col in age_columns:
    df_drug[col] = df_drug[col].round(0)

# Display the first few rows and data types to verify the changes
print("Data types of age-related columns after rounding:")
print(df_drug[age_columns].dtypes)
print("\nFirst few rows with rounded age values:")
df_drug.head()

Data types of age-related columns after rounding:
Q1_Age             float64
Q15_FirstUseAge    float64
dtype: object

First few rows with rounded age values:

,Respondent_ID,Q1_Age,Q2_Gender,Q3_Education,Q4_Employment,Q5_FamilyFinance,Q6_HomeLocation,Q7_FamilyHistory,Q8.1_Stress,Q8.2_PeerPressure,Q8.3_Normality,Q8.4_ExploreIdentity,Q8.5_HomeProblem,Q8.6_ConfidentToSayNo,Q9_Beliefs,Q10_MoralFailing,Q11_Penalties,Q12_FirstTimeMotivation,Q13_SocialAttitude,Q14_EverUsed,Q15_FirstUseAge,Q16_WeeklySpend,Q17_Cannabis,Q17_Cocaine,Q17_Ecstasy,Q17_Heroin,Q17_Meth,Q17_Prescription,Q17_Psychedelics,Q18_Frequency,Q19_Setting,Q20_InterestInHelp,Q21.1_SchoolEd,Q21.2_ParentalGuide,Q21.3_Commu,Q21.4_PublicCamp,Q21.5_MentalHealth
156,1,22.0,Female,2,Unemployed,Struggled to meet basic needs,A town,No,3.547701,3.088500,3.029201,3.309207,3.783110,3.559964,1.714293,2.421095,1.206965,To relieve stress or anxiety,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,17.0,66.305076,Yes,Yes,No,No,No,No,No,Once a week,At a friend's house,"Yes, considering",4.843801,4.890829,2.455424,3.979657,3.942842
10,2,18.0,Male,2,Unemployed,"Met basic needs, but with some difficulty",A rural area,Yes,2.054012,4.198952,2.209783,3.523866,2.445294,3.697164,2.077526,2.294953,2.120109,To relieve stress or anxiety,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,16.0,34.316943,Yes,No,No,No,Yes,No,Yes,1-3 times a month,At a friend's house,"Yes, considering",4.666446,4.936028,4.572778,4.850803,4.881922
82,3,20.0,Female,2,Student,"Comfortable, able to meet most needs",A town,Yes,1.856025,2.221508,1.203511,3.485828,2.034008,4.299885,2.841853,2.973249,3.605458,To relieve stress or anxiety,"Negative and stigmatized (e.g., seen as dangerous or a moral failing)",Yes,18.0,60.949473,Yes,No,No,No,No,No,No,1-3 times a month,At a friend's house,Not sure,3.291726,4.741208,2.045189,2.730219,3.795337
183,4,23.0,Female,3,Unemployed,"Met basic needs, but with some difficulty",A large city,No,2.652465,1.345772,1.482590,1.612894,2.593072,4.353729,2.661659,2.887705,1.902963,Curiosity,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,18.0,29.391190,Yes,No,No,No,No,No,No,Once a week,At a friend's house,Not sure,2.374819,2.566840,1.655841,1.889158,2.340117
107,5,21.0,Female,4,Self-employed,"Met basic needs, but with some difficulty",A large city,No,1.484414,2.710875,1.582764,1.739131,1.796326,3.645108,2.773359,4.208610,2.664736,To cope with boredom,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,19.0,26.006703,Yes,No,No,No,No,No,No,Less than once a month,"Outdoors (e.g., park, street)",No,3.924744,3.428508,2.124466,3.670147,4.086584

In [5]:
# Check for NaN values in the columns
print("NaNs in Q1_Age:", df_drug['Q1_Age'].isnull().sum())
print("NaNs in Q15_FirstUseAge:", df_drug['Q15_FirstUseAge'].isnull().sum())

# Find rows where the condition is False, which indicates a potential data error
inconsistent_data = df_drug[~(df_drug['Q1_Age'] >= df_drug['Q15_FirstUseAge'])]

print("\nRows with inconsistent age data:")
inconsistent_data[['Q1_Age', 'Q15_FirstUseAge']]

NaNs in Q1_Age: 0
NaNs in Q15_FirstUseAge: 0

Rows with inconsistent age data:

Empty DataFrame
Columns: [Q1_Age, Q15_FirstUseAge]
Index: []

In [6]:
# Define the education column and the mapping
education_mapping = {
    1: 'Did not complete Year 12',
    2: 'Completed Year 12 (VCE)',
    3: 'TAFE Qualification',
    4: 'Undergraduate University Degree',
    5: 'Postgraduate University Degree'
}

df_drug['Q3_Education'] = df_drug['Q3_Education'].map(education_mapping)
# Display the first few rows of the modified columns to verify the changes
df_drug[['Q3_Education']].head()

                        Q3_Education
156          Completed Year 12 (VCE)
10           Completed Year 12 (VCE)
82           Completed Year 12 (VCE)
183               TAFE Qualification
107  Undergraduate University Degree

In [7]:
# Define the Likert scale columns and the mapping
likert_columns = [
    'Q8.1_Stress', 'Q8.2_PeerPressure', 'Q8.3_Normality', 
    'Q8.4_ExploreIdentity', 'Q8.5_HomeProblem', 'Q8.6_ConfidentToSayNo', 
    'Q9_Beliefs', 'Q10_MoralFailing', 'Q11_Penalties'
]

likert_mapping = {
    1: 'Strongly Disagree',
    2: 'Disagree',
    3: 'Neutral',
    4: 'Agree',
    5: 'Strongly Agree'
}

# Round and map the values for each Likert scale column
for col in likert_columns:
    # Ensure the column exists before processing
    if col in df_drug.columns:
        df_drug[col] = df_drug[col].round(0).map(likert_mapping)

# Display the first few rows of the modified columns to verify the changes
df_drug[likert_columns].head()

,Q8.1_Stress,Q8.2_PeerPressure,Q8.3_Normality,Q8.4_ExploreIdentity,Q8.5_HomeProblem,Q8.6_ConfidentToSayNo,Q9_Beliefs,Q10_MoralFailing,Q11_Penalties
156,Agree,Neutral,Neutral,Neutral,Agree,Agree,Disagree,Disagree,Strongly Disagree
10,Disagree,Agree,Disagree,Agree,Disagree,Agree,Disagree,Disagree,Disagree
82,Disagree,Disagree,Strongly Disagree,Neutral,Disagree,Agree,Neutral,Neutral,Agree
183,Neutral,Strongly Disagree,Strongly Disagree,Disagree,Neutral,Agree,Neutral,Neutral,Disagree
107,Strongly Disagree,Neutral,Disagree,Disagree,Disagree,Agree,Neutral,Agree,Neutral

In [8]:
df_drug.head()

,Respondent_ID,Q1_Age,Q2_Gender,Q3_Education,Q4_Employment,Q5_FamilyFinance,Q6_HomeLocation,Q7_FamilyHistory,Q8.1_Stress,Q8.2_PeerPressure,Q8.3_Normality,Q8.4_ExploreIdentity,Q8.5_HomeProblem,Q8.6_ConfidentToSayNo,Q9_Beliefs,Q10_MoralFailing,Q11_Penalties,Q12_FirstTimeMotivation,Q13_SocialAttitude,Q14_EverUsed,Q15_FirstUseAge,Q16_WeeklySpend,Q17_Cannabis,Q17_Cocaine,Q17_Ecstasy,Q17_Heroin,Q17_Meth,Q17_Prescription,Q17_Psychedelics,Q18_Frequency,Q19_Setting,Q20_InterestInHelp,Q21.1_SchoolEd,Q21.2_ParentalGuide,Q21.3_Commu,Q21.4_PublicCamp,Q21.5_MentalHealth
156,1,22.0,Female,Completed Year 12 (VCE),Unemployed,Struggled to meet basic needs,A town,No,Agree,Neutral,Neutral,Neutral,Agree,Agree,Disagree,Disagree,Strongly Disagree,To relieve stress or anxiety,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,17.0,66.305076,Yes,Yes,No,No,No,No,No,Once a week,At a friend's house,"Yes, considering",4.843801,4.890829,2.455424,3.979657,3.942842
10,2,18.0,Male,Completed Year 12 (VCE),Unemployed,"Met basic needs, but with some difficulty",A rural area,Yes,Disagree,Agree,Disagree,Agree,Disagree,Agree,Disagree,Disagree,Disagree,To relieve stress or anxiety,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,16.0,34.316943,Yes,No,No,No,Yes,No,Yes,1-3 times a month,At a friend's house,"Yes, considering",4.666446,4.936028,4.572778,4.850803,4.881922
82,3,20.0,Female,Completed Year 12 (VCE),Student,"Comfortable, able to meet most needs",A town,Yes,Disagree,Disagree,Strongly Disagree,Neutral,Disagree,Agree,Neutral,Neutral,Agree,To relieve stress or anxiety,"Negative and stigmatized (e.g., seen as dangerous or a moral failing)",Yes,18.0,60.949473,Yes,No,No,No,No,No,No,1-3 times a month,At a friend's house,Not sure,3.291726,4.741208,2.045189,2.730219,3.795337
183,4,23.0,Female,TAFE Qualification,Unemployed,"Met basic needs, but with some difficulty",A large city,No,Neutral,Strongly Disagree,Strongly Disagree,Disagree,Neutral,Agree,Neutral,Neutral,Disagree,Curiosity,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,18.0,29.391190,Yes,No,No,No,No,No,No,Once a week,At a friend's house,Not sure,2.374819,2.566840,1.655841,1.889158,2.340117
107,5,21.0,Female,Undergraduate University Degree,Self-employed,"Met basic needs, but with some difficulty",A large city,No,Strongly Disagree,Neutral,Disagree,Disagree,Disagree,Agree,Neutral,Agree,Neutral,To cope with boredom,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,19.0,26.006703,Yes,No,No,No,No,No,No,Less than once a month,"Outdoors (e.g., park, street)",No,3.924744,3.428508,2.124466,3.670147,4.086584

In [ ]:
# Define the effectiveness scale columns and the mapping
effectiveness_columns = [
    'Q21.1_SchoolEd', 'Q21.2_ParentalGuide', 'Q21.3_Commu', 
    'Q21.4_PublicCamp', 'Q21.5_MentalHealth'
]

effectiveness_mapping = {
    1: 'Not effective at all',
    2: 'Not effective',
    3: 'Neutral',
    4: 'Effective',
    5: 'Very effective'
}

# Round and map the values for each effectiveness scale column
for col in effectiveness_columns:
    # Ensure the column exists before processing
    if col in df_drug.columns:
        df_drug[col] = df_drug[col].round(0).map(effectiveness_mapping)

# Display the first few rows of the modified columns to verify the changes
df_drug[effectiveness_columns].head()

,Q21.1_SchoolEd,Q21.2_ParentalGuide,Q21.3_Commu,Q21.4_PublicCamp,Q21.5_MentalHealth
156,Very effective,Very effective,Not effective,Effective,Effective
10,Very effective,Very effective,Very effective,Very effective,Very effective
82,Neutral,Very effective,Not effective,Neutral,Effective
183,Not effective,Neutral,Not effective,Not effective,Not effective
107,Effective,Neutral,Not effective,Effective,Effective

In [ ]:
df_drug.head()

,Respondent_ID,Q1_Age,Q2_Gender,Q3_Education,Q4_Employment,Q5_FamilyFinance,Q6_HomeLocation,Q7_FamilyHistory,Q8.1_Stress,Q8.2_PeerPressure,Q8.3_Normality,Q8.4_ExploreIdentity,Q8.5_HomeProblem,Q8.6_ConfidentToSayNo,Q9_Beliefs,Q10_MoralFailing,Q11_Penalties,Q12_FirstTimeMotivation,Q13_SocialAttitude,Q14_EverUsed,Q15_FirstUseAge,Q16_WeeklySpend,Q17_Cannabis,Q17_Cocaine,Q17_Ecstasy,Q17_Heroin,Q17_Meth,Q17_Prescription,Q17_Psychedelics,Q18_Frequency,Q19_Setting,Q20_InterestInHelp,Q21.1_SchoolEd,Q21.2_ParentalGuide,Q21.3_Commu,Q21.4_PublicCamp,Q21.5_MentalHealth
156,1,22.0,Female,Completed Year 12 (VCE),Unemployed,Struggled to meet basic needs,A town,No,Agree,Neutral,Neutral,Neutral,Agree,Agree,Disagree,Disagree,Strongly Disagree,To relieve stress or anxiety,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,17.0,66.305076,Yes,Yes,No,No,No,No,No,Once a week,At a friend's house,"Yes, considering",Very effective,Very effective,Not effective,Effective,Effective
10,2,18.0,Male,Completed Year 12 (VCE),Unemployed,"Met basic needs, but with some difficulty",A rural area,Yes,Disagree,Agree,Disagree,Agree,Disagree,Agree,Disagree,Disagree,Disagree,To relieve stress or anxiety,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,16.0,34.316943,Yes,No,No,No,Yes,No,Yes,1-3 times a month,At a friend's house,"Yes, considering",Very effective,Very effective,Very effective,Very effective,Very effective
82,3,20.0,Female,Completed Year 12 (VCE),Student,"Comfortable, able to meet most needs",A town,Yes,Disagree,Disagree,Strongly Disagree,Neutral,Disagree,Agree,Neutral,Neutral,Agree,To relieve stress or anxiety,"Negative and stigmatized (e.g., seen as dangerous or a moral failing)",Yes,18.0,60.949473,Yes,No,No,No,No,No,No,1-3 times a month,At a friend's house,Not sure,Neutral,Very effective,Not effective,Neutral,Effective
183,4,23.0,Female,TAFE Qualification,Unemployed,"Met basic needs, but with some difficulty",A large city,No,Neutral,Strongly Disagree,Strongly Disagree,Disagree,Neutral,Agree,Neutral,Neutral,Disagree,Curiosity,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,18.0,29.391190,Yes,No,No,No,No,No,No,Once a week,At a friend's house,Not sure,Not effective,Neutral,Not effective,Not effective,Not effective
107,5,21.0,Female,Undergraduate University Degree,Self-employed,"Met basic needs, but with some difficulty",A large city,No,Strongly Disagree,Neutral,Disagree,Disagree,Disagree,Agree,Neutral,Agree,Neutral,To cope with boredom,"Accepted and normalized (e.g., seen as a recreational or casual activity)",Yes,19.0,26.006703,Yes,No,No,No,No,No,No,Less than once a month,"Outdoors (e.g., park, street)",No,Effective,Neutral,Not effective,Effective,Effective

In [ ]:
# Define the condition where 'Q14_EverUsed' is 'No'
condition = df_drug['Q14_EverUsed'] == 'No'

# Identify columns for questions 15 through 20
# We can do this by checking if the column name starts with the relevant question numbers
columns_to_clear = [col for col in df_drug.columns if col.startswith(
    ('Q15', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20')
)]

# For rows where the condition is met, set the values in the identified columns to NaN
df_drug.loc[condition, columns_to_clear] = np.nan

# Display a sample of rows where 'Q14_EverUsed' is 'No' to verify the changes
print("Sample of rows where 'Q14_EverUsed' is 'No' after clearing subsequent answers:")
df_drug[df_drug['Q14_EverUsed'] == 'No'].head()

Sample of rows where 'Q14_EverUsed' is 'No' after clearing subsequent answers:

Empty DataFrame
Columns: [Respondent_ID, Q1_Age, Q2_Gender, Q3_Education, Q4_Employment, Q5_FamilyFinance, Q6_HomeLocation, Q7_FamilyHistory, Q8.1_Stress, Q8.2_PeerPressure, Q8.3_Normality, Q8.4_ExploreIdentity, Q8.5_HomeProblem, Q8.6_ConfidentToSayNo, Q9_Beliefs, Q10_MoralFailing, Q11_Penalties, Q12_FirstTimeMotivation, Q13_SocialAttitude, Q14_EverUsed, Q15_FirstUseAge, Q16_WeeklySpend, Q17_Cannabis, Q17_Cocaine, Q17_Ecstasy, Q17_Heroin, Q17_Meth, Q17_Prescription, Q17_Psychedelics, Q18_Frequency, Q19_Setting, Q20_InterestInHelp, Q21.1_SchoolEd, Q21.2_ParentalGuide, Q21.3_Commu, Q21.4_PublicCamp, Q21.5_MentalHealth]
Index: []

In [ ]:
df_drug.to_csv('stratified_drug_200_withText.csv', index=False)